org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# AGP domyślnie stempluje debug-APK jako testOnly=true, przez co file managery
# odmawiają instalacji ("Nie zainstalowano aplikacji"). Wyłączamy — sideload OK.
android.injected.testOnly=false
